from typing import Protocol, Optional
from src.domain.models.car import Car
from src.domain.models.part import Part
from src.domain.models.customer import Customer
 
 
class CarRepository(Protocol):
    def add(self, car: Car) -> None: ...
    def get_by_id(self, car_id: str) -> Optional[Car]: ...
    def list_all(self) -> list[Car]: ...
    def update(self, car: Car) -> None: ...
    def delete(self, car_id: str) -> None: ...
 
 
class PartRepository(Protocol):
    def add(self, part: Part) -> None: ...
    def get_by_id(self, part_id: str) -> Optional[Part]: ...
    def list_all(self) -> list[Part]: ...
    def update(self, part: Part) -> None: ...
    def delete(self, part_id: str) -> None: ...
 
 
class CustomerRepository(Protocol):
    def add(self, customer: Customer) -> None: ...
    def get_by_id(self, customer_id: str) -> Optional[Customer]: ...
    def list_all(self) -> list[Customer]: ...
    def update(self, customer: Customer) -> None: ...
    def delete(self, customer_id: str) -> None: ...